version: '3'

services:
 db:
   image: mysql:5.5.62
   environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
   ports:
     - 4306:3306
   volumes:
     - db-data:/var/lib/mysql
     - ./mysqlconf:/etc/mysql/conf.d

 web:
   build:
     context: .
     dockerfile: ./docker/development/Dockerfile
   environment: 
     MYSQL_ROOT_PASSWORD: 'pass'
   command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
   ports:
     - "3000:3000"
   volumes:
     - .:/note
     - "bundle:/bundle"
   links:
      - db
   tty: true
   stdin_open: true


volumes:
  db-data:
    driver: local
  bundle:
    driver: local