# MySQL. Versions 5.1.10 and up are supported.

default: &default
  adapter: mysql2
  encoding: utf8
  charset: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost
  database: note_list
  socket: /tmp/mysql.sock

development:
  <<: *default

test:
  <<: *default
  database: note_test

production:
  <<: *default
  database: note_list_production
  adapter:  mysql2
  encoding: utf8
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host:     <%= ENV['DB_HOSTNAME'] %>
  port:     <%= ENV['DB_PORT'] %>