# MySQL. Versions 5.1.10 and up are supported.

default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock
  host: localhost

development:
  <<: *default
  database: note_development

test:
  <<: *default
  database: note_test

production:
  <<: *default
  database: note_production
  username: note
  password: <%= ENV['NOTE_DATABASE_PASSWORD'] %>