# MySQL. Versions 5.1.10 and up are supported.

default: &default
  adapter: mysql2
  encoding: utf8
  charset: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root #<%= ENV['DATABASE_USERNAME'] %>
  password: #<%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOSTNAME'] %>
  database: note_list #<%= ENV['DATABASE_NAME'] %>
  socket: /tmp/mysql.sock
  #port: 3306

development:
  <<: *default

test:
  <<: *default
  database: note_test

production:
  <<: *default
  database: note_production
  username: note
  password: <%= ENV['NOTE_DATABASE_PASSWORD'] %>